### ISSUE TITLE
Getting TypeError

### ISSUE THREAD

**Issue by cameronjroe** [MoOx/metalsmith-rss#1]
```
TypeError: item.categories.forEach is not a function
    at /Users/cameronjroe/Dropbox/_freelance/spider-strategies/spiderstrategies.com/node_modules/rss/lib/index.js:71:25
    at Array.forEach (native)
    at generateXML (/Users/cameronjroe/Dropbox/_freelance/spider-strategies/spiderstrategies.com/node_modules/rss/lib/index.js:63:16)
    at RSS.xml (/Users/cameronjroe/Dropbox/_freelance/spider-strategies/spiderstrategies.com/node_modules/rss/lib/index.js:185:17)
    at Ware.<anonymous> (/Users/cameronjroe/Dropbox/_freelance/spider-strategies/spiderstrategies.com/node_modules/metalsmith-rss/dist/index.js:69:33)
    at Ware.<anonymous> (/Users/cameronjroe/Dropbox/_freelance/spider-strategies/spiderstrategies.com/node_modules/wrap-fn/index.js:45:19)
    at Immediate.next (/Users/cameronjroe/Dropbox/_freelance/spider-strategies/spiderstrategies.com/node_modules/ware/lib/index.js:85:20)
    at Immediate._onImmediate (/Users/cameronjroe/Dropbox/_freelance/spider-strategies/spiderstrategies.com/node_modules/wrap-fn/index.js:121:18)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

**Comment by MoOx** [comment]
It seems your version of node does not support forEach.
Try upgrading to a recent version.

**Comment by cameronjroe** [comment]
I just upgraded to v5.0.0 with the same error. Which version are you running?

**Comment by cameronjroe** [comment]
That's the stable version of node by the way.

**Comment by MoOx** [comment]
Hum... So I guess your "categories" is undefined. Are you using metalsmith-collections ?

**Comment by cameronjroe** [comment]
Yeah, I have a posts collection defined.

**Comment by MoOx** [comment]
The error comes from "rss" package, not this one. Please double check the feedOptions you are providing https://github.com/dylang/node-rss#feedoptions.
It seems "categories" is not an array as "rss" expect.
Btw when you open an issue, stack trace is not enough. Provide your configuration and/or code is better.

**Comment by cameronjroe** [comment]
`rss: {
    feedOptions: {
      title: 'Spider Strategies',
      site_url: 'http://spiderstrategies.com'
    }
  }`

**Comment by MoOx** [comment]
Do you have a "categories" field for your post or something?

**Comment by cameronjroe** [comment]
I do. Does this mean I can't use that?

**Comment by MoOx** [comment]
Not sure. Is this an array?

**Comment by MoOx** [comment]
If not it should https://github.com/dylang/node-rss#itemoptions

**Comment by cameronjroe** [comment]
I got it. There wasn't an array for the categories. Works now. Thanks.
